#!/bin/sh

name=base-files
version=0.1
revision=1
source_dir="base-files"

package() {
    cp -r ${source_dir}/. "${dest_dir}"/
    # find "${dest_dir}/" -type f -name ".keep" -delete

    for dir in "${dest_dir}/*/"; do
        dir=${dir%/}

        file_count=$(ls -A "$dir" | grep -v "^\.keep$" | wc -l)

        if [ "$file_count" -gt 0 ]; then
            if [ -f "$dir/.keep" ]; then
                rm "$dir/.keep"
            fi
        fi
    done
}
