#!/bin/sh

name=glibc-base
from_source=glibc
revision=1
hostdeps="gcc-stage1"
deps="linux-headers"

configure() {
    cp -rp "${source_dir}"/. ./
    mkdir -p build && cd build

        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
    ../configure \
        --prefix="${prefix}" \
        --host=${OS_TRIPLET} \
        --build=$(../scripts/config.guess) \
        --with-headers="${sysroot_dir}${prefix}/include" \
        --disable-multilib \
        --disable-werror \
        --disable-nscd \
        --enable-kernel=5.4 \
        --disable-sanity-checks \
        libc_cv_forced_unwind=yes \
        libc_cv_c_cleanup=yes
}

package() {
    cd build
    DESTDIR="${dest_dir}" make install-headers
    touch "${dest_dir}${prefix}/include/gnu/stubs.h"

    make csu/subdir_lib
    mkdir -p "${dest_dir}${prefix}/lib"
    install csu/crt1.o csu/Scrt1.o csu/crti.o csu/crtn.o "${dest_dir}${prefix}/lib"

    ${OS_TRIPLET}-gcc -nostdlib -nostartfiles -shared -x c /dev/null \
        -o "${dest_dir}${prefix}/lib/libc.so"
}
