#!/bin/sh

name=shadow
version=4.19.4
revision=1
tarball_url="https://github.com/shadow-maint/shadow/releases/download/${version}/shadow-${version}.tar.gz"
tarball_blake2b="44ec01d4e3ce25dec9500cf0fbcf436a81cec72fa4fffea06357d61f9b2b900bdad421981931f4900f654ae62d0697acd318c01933b280a26fbed1c28a0231db"
hostdeps="gcc pkg-config"
deps="core-libs libbsd" # pam"

configure() {
    # --with-libpam \

    autotools_configure \
        --without-libpam \
        --enable-shadowgrp \
        --enable-shared \
        --disable-static \
        --without-selinux \
        --without-audit \
        --disable-nls \
        --disable-logind \
        --with-group-name-max-length=32
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    post_package_strip
}
