#!/bin/sh

name=sudo
version=1.9.17p2
revision=1
tarball_url="https://www.sudo.ws/dist/sudo-${version}.tar.gz"
tarball_blake2b="dd42ff4fd571ba8489cc59d71a09c7e0483d21daf9faf7e697beedc04d9f170b01e60446af179c949a3da115b616fbec07aff8fbf8b7d502161c24d1b35b7a69"
hostdeps="gcc pkg-config"
deps="core-libs pam"

configure() {
    autotools_configure \
        --libexecdir=/usr/lib \
        --with-secure-path \
        --with-env-editor \
        --docdir=/usr/share/doc/sudo-1.9.17p2 \
        --with-passprompt="[sudo] password for %p: "
}

build() {
    make -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" make install

    mkdir -p "${dest_dir}"/etc/sudoers.d
    cp -v "${base_dir}"/support/sudo/* "${dest_dir}"/etc/sudoers.d/

    post_package_strip
}
