#!/bin/sh

name=util-linux
version=2.42
revision=1
tarball_url="https://www.kernel.org/pub/linux/utils/util-linux/v${version}/util-linux-${version}.tar.xz"
tarball_blake2b="531b79bbec272cf1007c55ff4042b5e1b14bcc0dc098e54e4b76ea2e70c785fc763f96686ad8cea5ea9c0f7190794f4d828b7742e3aa18a0c3ef506d34e9d465"
hostdeps="gcc pkg-config"
deps="core-libs ncurses readline zlib file pcre2 python" # pam"

configure() {
    meson_configure \
        -Dbuild-login=disabled \
        -Dbuild-su=disabled \
        -Dbuild-chfn-chsh=disabled \
        -Dbuild-newgrp=disabled \
        -Dbuild-nologin=disabled \
        -Dbuild-runuser=disabled \
        -Dbuild-sulogin=enabled
}

build() {
    meson compile -j${parallelism}
}

package() {
    DESTDIR="${dest_dir}" meson install --no-rebuild

    post_package_strip
}
