#!/bin/sh

name=gcc
from_source=gcc
revision=1
hostdeps="binutils"
deps="glibc"

configure() {
    cp -rp "${source_dir}"/. ./
    mkdir -p build && cd build

        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
    ../configure \
        --prefix="${prefix}" \
        --target=${OS_TRIPLET} \
        --with-sysroot="${sysroot_dir}" \
        --enable-languages=c,c++,lto \
        --disable-bootstrap \
        --disable-multilib \
        --disable-nls \
        --enable-initfini-array \
        --enable-threads=posix \
        --enable-shared \
        --enable-host-shared
}

build() {
    cd build
    make -j${parallelism}
}

package() {
    cd build
    DESTDIR="${dest_dir}" make install
}