#!/bin/sh

name=gcc-stage1
from_source=gcc
revision=1
hostdeps="binutils"

configure() {
    cp -rp "${source_dir}"/. ./
    mkdir -p build && cd build

        CFLAGS="$HOST_CFLAGS" \
        CXXFLAGS="$HOST_CXXFLAGS" \
        LDFLAGS="$HOST_LDFLAGS" \
        CFLAGS_FOR_TARGET="$TARGET_CFLAGS" \
        CXXFLAGS_FOR_TARGET="$TARGET_CXXFLAGS" \
    ../configure \
        --target=${OS_TRIPLET} \
        --prefix="${prefix}" \
        --with-glibc-version=2.43 \
        --with-sysroot="${sysroot_dir}" \
        --with-newlib \
        --without-headers \
        --enable-default-pie \
        --enable-default-ssp \
        --disable-nls \
        --disable-shared \
        --disable-multilib \
        --disable-threads \
        --disable-libatomic \
        --disable-libgomp \
        --disable-libquadmath \
        --disable-libssp \
        --disable-libvtv \
        --disable-libstdcxx \
        --enable-languages=c \
        --disable-bootstrap
}

build() {
    cd build
    make -j${parallelism}
}

package() {
    cd build
    DESTDIR="${dest_dir}" make install
}
